# -*- coding: utf-8 -*-
"""01_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcUBgv6edaOcDwNQrKQRzP0hd-Wkaqjs

# **Necessary Imports**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Interactive visualization
import plotly.express as px
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.figure_factory as ff

from google.colab import drive
drive.mount('/content/drive')
# Handle warnings
import warnings
warnings.filterwarnings('ignore')
plt.style.use('ggplot')
# %matplotlib inline

"""# **Exploratory Data Analysis (EDA)**"""

# Reading the file
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/customer-telco-churn/data/raw/telco-customer-churn.csv')

# Check for all the columns
columns = list(df.columns)
columns

# View first few records
df.head()

# Check for null values
df.info()

df[df['tenure'] == 0][['tenure', 'TotalCharges']] # an empty string for no tenure

# Convert the TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.isna().sum()

# Fill with monthly charges
df['TotalCharges'].fillna(df['MonthlyCharges'], inplace=True)

df.isna().sum()

# Check the dataframe's dimensions
df.shape

df.isna().sum()

# Check for duplicates
print(df.duplicated().sum())

# Get all value counts for objects to check for structural errors
for column in df.columns:
  if df[column].dtype == 'object':
    print(f"{column}:")
    print(df[column].value_counts())

def distribution_curve(feature):
  data = [df[feature]]
  fig = ff.create_distplot(data, group_labels=[feature], show_hist=False, show_rug=False)
  fig.update_layout(
      title=f"Distribution of {feature}",
      xaxis_title=feature,
      yaxis_title="Density")
  fig.show()

distribution_curve('MonthlyCharges')

distribution_curve("tenure")

distribution_curve("TotalCharges")

# Churn rate by contract type
contract_churned = pd.crosstab(df['Contract'], df['Churn'], normalize='index') * 100
fig = px.bar(contract_churned, barmode='group',
             title='Churn Rate by Contract Type',
             labels={'value': 'Percentage(%)', 'Contract': 'Contract Type'})
fig.show()

def churned_distribution(feature):
  # Filter only churned customers
  churned = df[df['Churn'] == 'Yes']

  # Count churned customers by feature
  churn_by_feature = churned[feature].value_counts()

  # Pie chart
  fig = px.pie(
      names=churn_by_feature.index,
      values=churn_by_feature.values,
      title=f'Churn Distribution by {feature} (Only Churned Customers)',
      hole=0.3  # optional: makes it a donut chart
  )

  fig.update_traces(textposition='inside', textinfo='percent+label')
  fig.show()

churned_distribution("Contract")

# Tenure distribution by churn status
fig = px.histogram(df, x='tenure', y='Churn',
                   barmode='overlay', title='Tenure Distribution of Churned vs Retained Customers',
                   opacity=0.6)
fig.show()

# Monthly charges by internet service and churn
fig = px.box(df, x='InternetService', y='MonthlyCharges', color='Churn',
             title='Distribution of Monthly Charges vs Internet Service by Churn')
fig.show()

churned_distribution('InternetService')

def plot_churn(feature):
  """Method to plot a feature by its churn"""
  churn = pd.crosstab(df[feature], df['Churn'], normalize='index') * 100
  fig = px.bar(churn, barmode='group',
             title='Churn Rate by ' + feature,
             labels={'value': 'Churn Rate (%)'})
  fig.show()

plot_churn('InternetService')

# Churn rate by payment method
plot_churn('PaymentMethod')

churned_distribution('PaymentMethod')

plot_churn('SeniorCitizen')

churned_distribution('SeniorCitizen')

plot_churn('StreamingMovies')

churned_distribution('StreamingMovies')

plot_churn('StreamingTV')

churned_distribution('StreamingTV')

plot_churn('TechSupport')

churned_distribution('TechSupport')

plot_churn('OnlineSecurity')

churned_distribution('OnlineSecurity')

plot_churn('OnlineBackup')

churned_distribution('OnlineBackup')

plot_churn('DeviceProtection')

churned_distribution('DeviceProtection')

plot_churn('PaperlessBilling')

churned_distribution('PaperlessBilling')

plot_churn('MultipleLines')

churned_distribution('MultipleLines')

plot_churn('Dependents')

churned_distribution('Dependents')

plot_churn('Partner')

churned_distribution('Partner')

plot_churn("gender")

churned_distribution("gender")

"""# **Churn Distribution**"""

churns = df['Churn'].value_counts()
plt.figure(figsize=(5, 4))
fig = px.pie(values=churns.values, names=churns.index, title='Churn Distribution')
fig.show()

"""# **Distribution of Churn by Each Feature**"""

# Generate summary statistics
df.describe()

# Summary statistics for numerical features
df.describe(include='object')

# Payment method distribution
px.histogram(df, x='PaymentMethod', color='Churn', title='Churn by Payment Method')

# Distribution of churn by internet service
px.histogram(df, x='InternetService', color='Churn', title='Churn by Internet Service')

# Distribution of Dependents
px.histogram(df, x='Churn', color='Dependents', title='Churn by Dependents')

# Churn by Online Security
px.histogram(df, x='Churn', color='OnlineSecurity', title='Churn by Online Security')

# Churn by Tech Support
px.histogram(df, x='Churn', color='TechSupport', title='Churn by Tech Support')

# Churn by online backup
px.histogram(df, x='Churn', color='OnlineBackup', title='Churn by Online Backup')

# Churn by Paperless Billing
px.histogram(df, x='Churn', color='PaperlessBilling', title='Churn by Paperless Billing')

# Churn by Device Protection
px.histogram(df, x='Churn', color='DeviceProtection', title='Churn by Device Protection')

# Churn by Multiple Lines
px.histogram(df, x='Churn', color='MultipleLines', title='Churn by Multiple Lines')

px.histogram(df, x='Churn', color='StreamingTV', title='Churn by Streaming TV')

px.histogram(df, x='Churn', color='StreamingMovies', title='Churn by Streaming Movies')

fig = px.box(df, x='Churn', y='MonthlyCharges', color='Churn',
             title='Monthly Charges by Churn')
fig.show()

# Tenure against total charges by churn
fig = px.scatter(df, x='tenure', y='TotalCharges', color='Churn',
                 hover_data=['Contract', 'PaymentMethod'],
                 title='Tenure vs Total Charges by Churn')
fig.show()

# Stacked barcharts
def plot_barchart_vs_churn(feature):
  plt.figure(figsize=(8,5))
  sns.countplot(data=df, x=feature, hue='Churn')
  plt.title(f"{feature} vs Churn")
  plt.xticks(rotation=45)
  plt.show()

sns.distplot(df['MonthlyCharges'])
plt.show()

sns.kdeplot(data=df, x='MonthlyCharges', hue='Churn', multiple='stack')
plt.show()

fig = px.box(df, x='Churn', y='MonthlyCharges', color='Partner')
fig.show()

plt.figure()
plt.title("Distribution of Total Charges by Churn")
sns.kdeplot(data=df, x='TotalCharges', hue='Churn', fill=True)
plt.plot()

"""# **Boxplots**"""

def boxplot(feature):
  """
  Plots a boxplot for a numerical feature by churn
  """
  fig = px.box(
  df,
  x='Churn',
  y=feature,
  color='Churn',
  title=f"{feature} by Churn",
  points='all'
  )
  fig.show()

boxplot("TotalCharges")

# Tenure by Churn
boxplot("tenure")

# Monthly charges vs Churn
boxplot("MonthlyCharges")

"""# **Scatterplots**"""

def scatter(feature1, feature2):
  """
  Plots a scatterplot between 2 numerical features
  """
  fig = px.scatter(
      df,
      x=feature1,
      y=feature2,
      color='Churn',
      opacity=0.6,
      hover_data=df.columns,
      trendline='ols',
      title=f"{feature1} vs {feature2} by Churn"
  )
  fig.show()

scatter("tenure", "MonthlyCharges")

scatter("tenure", "TotalCharges")

scatter("MonthlyCharges", "TotalCharges")

# Function to plot scatterplots for 2 variables by a categorical feature
def facet_scatter(feature1, feature2, facet_feature):
  """
  Plots scatterplots for 2 variables by a categorical feature
  """
  fig = px.scatter(
      df,
      x=feature1,
      y=feature2,
      color="Churn",
      facet_col=facet_feature,
      opacity=0.6,
      hover_data=df.columns,
      title=f"{feature1} vs {feature2} by {facet_feature}"
  )
  fig.update_traces(marker=dict(size=5))
  fig.show()

facet_scatter("tenure", "MonthlyCharges", "InternetService")

facet_scatter("tenure", "MonthlyCharges", "Contract")

facet_scatter("tenure", "MonthlyCharges", "PaymentMethod")

sns.histplot(data=df, x='TotalCharges', kde=True, stat='density', color='purple')

def plot_density(feature):
  """
  Plots a density plot of a numerical feature by churn
  """
  sns.kdeplot(data=df, x=feature, hue='Churn', multiple='stack', fill=True, alpha=0.5)

  plt.title(f'Density Plot of {feature} by Churn')
  plt.xlabel(feature)
  plt.ylabel('Density')
  plt.grid(True)
  plt.show()

plot_density("tenure")

# Correlation heatmap
df_corr_numeric = df.corr(numeric_only=True)

plt.figure(figsize=(12,8))
fig = px.imshow(
    df_corr_numeric,
    color_continuous_scale = 'RdBu_r',  # diversing color scale
    title = "Feature Correlation Heatmap",
    aspect="auto",
    text_auto=True  # show correlation values
)
fig.show()

# Violin plots
def violin_plot(x, y, color):
  """
  Plots a violin plot of numerical features by a categorical feature
  """
  fig = px.violin(df, x=x, y=y, color=color,
                      box=True, points='all',
                      title=f"Customer {y} vs {x}")
  fig.show()

violin_plot("Churn", "MonthlyCharges", "gender")

violin_plot("Churn", "MonthlyCharges", "Churn")

violin_plot("PaymentMethod", "TotalCharges", "PaymentMethod")

violin_plot("Contract", "MonthlyCharges", "Contract")

def kde(feature):
  sns.kdeplot(data=df, x=feature, hue='Churn', fill=True)

kde("tenure")

def jointplot_kde(feature1, feature2):
  """
  Plots a kde jointplot between 2 numerical features by churn
  """
  sns.jointplot(data=df, x=feature1, y=feature2, hue='Churn', kind='kde', fill=True)

jointplot_kde("tenure", "MonthlyCharges")

jointplot_kde("tenure", "TotalCharges")

def jointplot_hex(feature1, feature2):
  """
  Plots a hexagonal jointplot between 2 numerical features
  """
  sns.jointplot(data=df, x=feature1, y=feature2, kind='hex', color='purple')
  plt.show()

jointplot_hex("tenure", "MonthlyCharges")

jointplot_hex("tenure", "TotalCharges")

# Handling total charges
# df['Churn'] = df['Churn'].apply(lambda x: 1 if x == "Yes" else 0)
# Remove unimportant features
# df = df.drop('customerID', axis=1)

# export and remove the unnamed column
df.to_csv("/content/drive/MyDrive/Colab Notebooks/customer-telco-churn/data/cleaned/cleaned_data.csv", index=False)

# Heatmaps
def cross_tab(feature1, feature2):
  """
  Plots a heatmap between two categorical variables
  """
  cross_tab = pd.crosstab(df[feature1], df[feature2])
  sns.heatmap(cross_tab, annot=True, fmt='d', cmap='Blues')
  plt.title(f"{feature1} vs {feature2}")
  plt.show()

cross_tab("InternetService", "OnlineSecurity")

cross_tab("Contract", "PaymentMethod")

# which services paired with tech support
cross_tab("InternetService", "TechSupport")

# Who subscribes to streaming based on internet type
cross_tab("InternetService", "StreamingMovies")

cross_tab("InternetService", "StreamingTV")

# How service usage differs from seniors
cross_tab("SeniorCitizen", "InternetService")

# which contract goes with the internet service
cross_tab("Contract", "InternetService")

cross_tab("SeniorCitizen", "PaymentMethod")

cross_tab("SeniorCitizen", "StreamingMovies")

