# -*- coding: utf-8 -*-
"""02a_Neural_Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_KJ7efntU8fQYIUqi9eB94dEo8kNk88

# **Necessary Imports**
"""

!pip install keras_tuner
!pip install scikeras

# Numerical arrays
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Neural network
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split, StratifiedKFold
import keras_tuner

# Data Preprocessing
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder, StandardScaler
from sklearn.feature_selection import mutual_info_classif, SelectKBest
from sklearn.utils.class_weight import compute_class_weight
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Model evaluation
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve, ConfusionMatrixDisplay,
                              accuracy_score, precision_recall_curve)

# Hyperparameter tuning
from keras_tuner import RandomSearch

import shap
from google.colab import drive
drive.mount('/content/drive')

# Hide warnings
import warnings
warnings.filterwarnings('ignore')

"""# 1. **Data Loading and Splitting**"""

# Reading the data
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/customer-telco-churn/data/cleaned/cleaned_data.csv')

# remove gender and unnamed column since they are not needed
df = df.drop(["customerID", "gender"], axis=1)
df['Churn'] = df['Churn'].apply(lambda x: 1 if x == "Yes" else 0)

# Seperate independent and dependent variables
X = df.drop('Churn', axis=1)
y = df['Churn']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y) # equal proportions of each class

# Get categorical (nominal + ordinal), numerical features for later preprocessing
numerical_features = X_train.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X_train.select_dtypes(include=['object']).columns.drop('Contract')  # Exclude the ordinal column
ordinal_feature = ['Contract']  # Contracts get better from Month-to-month to One year to Two year

"""# **2. Create Preprocessing Pipeline**"""

# numerical
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())    # standard scaler for neural network
])

# Categorical (excluding ordinal)
categorical_transformer = Pipeline(steps=[
    ('encoder', OneHotEncoder(handle_unknown='ignore')) # encode nominal features
])

# Ordinal feature
ordinal_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder(categories=[
        ['Month-to-month', 'One year', 'Two year']
    ]))
])

# Create the preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
        ('ord', ordinal_transformer, ordinal_feature),
        ('num', numerical_transformer, numerical_features)
    ]
)

def clean_feature_names(feature_names):
    """
    Clean feature names by removing transformer prefixes
    """
    cleaned_names = []

    for name in feature_names:
        # Remove transformer prefixes
        if name.startswith('cat__'):
            name = name[5:]  # Remove 'cat__'
        elif name.startswith('ord__'):
            name = name[5:]  # Remove 'ord__'
        elif name.startswith('remainder__'):
            name = name[11:]  # Remove 'remainder__'
        elif name.startswith('num__'):
            name = name[5:]

        # Replace underscores with spaces for better readability
        name = name.replace('_', ' ')

        # Capitalize each word
        name = ' '.join(word.capitalize() for word in name.split())

        cleaned_names.append(name)

    return cleaned_names

# Fit the preprocessor
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

feature_names_raw = preprocessor.get_feature_names_out()
feature_names = clean_feature_names(feature_names_raw)

"""# **3. Feature Selection with Mutual Information**"""

# Comoute mi scores
mi_scores = mutual_info_classif(X_train, y_train, random_state=42)

mi_df = pd.DataFrame({
    'Feature': feature_names,
    'MI Score': mi_scores
}).sort_values('MI Score', ascending=False)

mi_df.head(20)

# Select the top 20 features only
selector = SelectKBest(score_func=mutual_info_classif, k=20)
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

"""# **4. Creating the Neural Network**"""

def create_nn(input_dim,
              hidden_layers,
              dropout_rate,
              learning_rate,
              l2_reg):
  """
  Used to create the neural network with layers, dropout, batch norm and regularization
  """
  model = tf.keras.models.Sequential()

  # Input layer
  model.add(tf.keras.layers.Input(shape=(input_dim, )))

  # Add hidden layers
  for i, neurons in enumerate(hidden_layers):
    model.add(tf.keras.layers.Dense(
        neurons,
        activation='relu',
        kernel_regularizer=tf.keras.regularizers.l2(l2_reg),
        name=f'hidden_layer_{i+1}'
    ))
    model.add(tf.keras.layers.BatchNormalization(name=f'batch_norm_{i+1}'))

    # dropout for regularization
    model.add(tf.keras.layers.Dropout(dropout_rate, name=f'dropout_{i+1}'))


  # Output layer
  model.add(tf.keras.layers.Dense(1, activation='sigmoid', name='output_layer'))

  # Compile model
  optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
  model.compile(
      optimizer=optimizer,
      loss='binary_crossentropy',
      metrics=['accuracy',
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall'),
      tf.keras.metrics.AUC(name='auc'),
      tf.keras.metrics.AUC(name='prc', curve='PR')  # precision-recall prc
      ]
  )

  return model

# Get the dimension required for creating the model
input_dim = X_train_selected.shape[1]

# Create the model
neural_network = create_nn(
    input_dim=input_dim,
    hidden_layers=[128,64,32],
    dropout_rate=0.3,
    learning_rate=0.001,
    l2_reg=0.001
)

# Summary of the created model
neural_network.summary()

def get_callbacks(patience=15):
  """
  To get the callbacks for early stopping
  """
  early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_auc',
    patience=patience,    # if it does not improve, then stop after patience epochs
    restore_best_weights=True,  # return to the best model without ending at the last
    verbose=1,
    mode='max'    # treats higher values as improvements
  )

  return early_stopping

# Receive the callbacks
callbacks = get_callbacks()

# Handle class imbalance

class_weights = compute_class_weight(
    'balanced',   # treat the minority class as more important
    classes=np.unique(y_train),   # exact order class labels
    y=y_train   # frequencies calculated here
)

class_weight_dict = {0: class_weights[0], 1: class_weights[1]}  # returned a numpy array

"""# **5. Training the Neural Network**"""

# Train the network
batch_size = 32
epochs = 100
validation_split = 0.2

trained_model = neural_network.fit(
    X_train_selected,
    y_train,
    batch_size=batch_size,
    epochs=epochs,
    validation_split=validation_split,
    callbacks=callbacks,
    class_weight=class_weight_dict, # handle imbalanced data
    verbose=0
)

"""# **6. Evaluating the Neural Network**"""

# visualize training history
def visualize_history(history):
  """
  Used to visualize the training history of the model
  """

  fig, axes = plt.subplots(2, 3, figsize=(18,10))

  # loss
  axes[0, 0].plot(history.history['loss'], label='Training loss')
  axes[0, 0].plot(history.history['val_loss'], label='Validation loss')
  axes[0, 0].set_title('Model Loss')
  axes[0, 0].set_xlabel('Epoch')
  axes[0, 0].set_ylabel('Loss')
  axes[0, 0].legend()
  axes[0, 0].grid(True, alpha=0.3)

  # accuracy
  axes[0, 1].plot(history.history['accuracy'], label='Training accuracy')
  axes[0, 1].plot(history.history['val_accuracy'], label='Validation accuracy')
  axes[0, 1].set_title('Model Accuracy')
  axes[0, 1].set_xlabel('Epoch')
  axes[0, 1].set_ylabel('Accuracy')
  axes[0, 1].legend()
  axes[0, 1].grid(True, alpha=0.3)

  # AUC
  axes[0, 2].plot(history.history['auc'], label='Training AUC')
  axes[0, 2].plot(history.history['val_auc'], label='Validation AUC')
  axes[0, 2].set_title('ROC-AUC')
  axes[0, 2].set_xlabel('Epoch')
  axes[0, 2].set_ylabel('AUC')
  axes[0, 2].legend()
  axes[0, 2].grid(True, alpha=0.3)

  # precision
  axes[1, 0].plot(history.history['precision'], label='Training precision')
  axes[1, 0].plot(history.history['val_precision'], label='Validation precision')
  axes[1, 0].set_title('Model Precision')
  axes[1, 0].set_xlabel('Epoch')
  axes[1, 0].set_ylabel('Precision')
  axes[1, 0].legend()
  axes[1, 0].grid(True, alpha=0.3)

  # recall
  axes[1, 1].plot(history.history['recall'], label='Training recall')
  axes[1, 1].plot(history.history['val_recall'], label='Validation recall')
  axes[1, 1].set_title('Model Recall')
  axes[1, 1].set_xlabel('Epoch')
  axes[1, 1].set_ylabel('Recall')
  axes[1, 1].legend()
  axes[1, 1].grid(True, alpha=0.3)

  plt.tight_layout()
  fig.delaxes(axes[1, 2])
  plt.show()

def plot_ks_chart(y_true, y_pred_proba, model_name):
  """
  Plots KS Chart for binary classification of churn
  """

  # Calculate KS Statistic
  fpr, tpr, thresholds = roc_curve(y_true, y_pred_proba)
  ks_values = tpr - fpr
  ks_statistic = np.max(ks_values)
  ks_idx = np.argmax(ks_values)
  ks_threshold = thresholds[ks_idx]

  # Create dataframe for plotting
  df_ks = pd.DataFrame({
      'Thresholds': thresholds,
      'TPR': tpr,
      'FPR': fpr,
      'KS': ks_values
  })

  # Plot
  plt.figure(figsize=(10,6))
  sns.lineplot(x='Thresholds', y='TPR', data=df_ks, label='True Positive Rate (TPR)', color='blue')
  sns.lineplot(x='Thresholds', y='FPR', data=df_ks, label='False Positive Rate (FPR)', color='red')

  # Shade the KS region
  plt.fill_between(df_ks['Thresholds'], df_ks['TPR'], df_ks['FPR'],
                   where=(df_ks['TPR'] >= df_ks['FPR']),
                   color='gray', alpha=0.2, interpolate=True)

  # Makr KS point
  plt.scatter(ks_threshold, tpr[ks_idx], color='green', s=50, label=f'KS Point ({ks_statistic:.3f})')
  plt.scatter(ks_threshold, fpr[ks_idx], color='green', s=50)

  # Style the plot
  plt.title(f"KS Chart - {model_name}", fontsize=14)
  plt.xlabel("Thresholds")
  plt.ylabel("Cumulative Percentage")
  plt.xlim([0,1])
  plt.ylim([0,1])
  plt.grid(True)
  plt.legend()
  plt.show()

visualize_history(trained_model)

plot_ks_chart(y_test, neural_network.predict(X_test_selected), "Base Neural Network")

def evaluate_nn(model, X_test, y_test, threshold=0.5):
  """
  Used to evaluate the neural network model using a threshold
  """
  y_pred_prob = model.predict(X_test)
  y_predictions = (y_pred_prob > threshold).astype(int)

  print(classification_report(y_test, y_predictions, target_names=['No churn', 'Churn']))
  print("AUC:", roc_auc_score(y_test, y_pred_prob))

  # confusion matrix
  cm = confusion_matrix(y_test, y_predictions)
  disp = ConfusionMatrixDisplay(confusion_matrix=cm)

  # Display the confusion matrix
  disp.plot()
  plt.show()

def plot_tpr_fpr(y_test, y_pred_prob):
  """
  Plot ROC Curves
  """
  fpr, tpr, thresholds_roc = roc_curve(y_test, y_pred_prob)

  precision, recall, threshold_pr = precision_recall_curve(y_test, y_pred_prob)

  fig, axes = plt.subplots(1, 2, figsize=(10,6))

  # ROC Curve
  axes[0].plot(fpr, tpr, color='blue', lw=2, label='ROC Curve')
  axes[0].set_xlabel('False Positive Rate (FPR)')
  axes[0].set_ylabel('True Positive Rate (TPR)')
  axes[0].set_title('Receiver Operating Characteristic (ROC) Curve')
  axes[0].legend(loc='lower right')
  axes[0].grid(alpha=0.5)

  # Precision recall
  axes[1].plot(recall, precision, color='green', lw=2, label='PR Curve')
  axes[1].set_xlabel('Recall')
  axes[1].set_ylabel('Precision')
  axes[1].set_title('Precision-Recall Curve')
  axes[1].legend(loc='lower left')
  axes[1].grid(alpha=0.5)

  plt.tight_layout()

  plt.show()

evaluate_nn(neural_network, X_test_selected, y_test)

evaluate_nn(neural_network, X_test_selected, y_test, threshold=0.4)

evaluate_nn(neural_network, X_test_selected, y_test, threshold=0.3)

plot_tpr_fpr(y_test, neural_network.predict(X_test_selected))



"""# **7. Hyperparameter Tuning**"""

input_dim = X_train_selected.shape[1]

def tune(parameter):
  """
  Used to tune the neural network
  """
  global input_dim
  model = keras.Sequential()
  model.add(tf.keras.layers.Input(shape=(input_dim, ))) # input_dim for number of features

  # Tune number of layers
  for i in range(parameter.Int('num_layers', 1, 3)): # try 1 to 3 hidden layers (different amounts may be underfitting/overfitting)
    model.add(tf.keras.layers.Dense(
        units=parameter.Int(f'units_{i}', min_value=32, max_value=256, step=32),

        # relu to prevent vanising gradients and suited for hidden layers
        activation='relu',

        # Prevent overfitting
        kernel_regularizer=tf.keras.regularizers.l2(parameter.Float('l2', 1e-5, 1e-1, sampling='log'))
    ))
    model.add(tf.keras.layers.Dropout(parameter.Float('dropout', 0.1, 0.5, step=0.1)))

    # Normalize output of previous layers
    model.add(tf.keras.layers.BatchNormalization())

  model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

  model.compile(

                # Tune learning rate with log values
      optimizer=tf.keras.optimizers.Adam(
          learning_rate=parameter.Float('learning_rate', 1e-4, 1e-2, sampling='log')
      ),
      loss='binary_crossentropy', # for binrary classification
      metrics=['accuracy',
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall'),
      tf.keras.metrics.AUC(name='auc')] # better for imbalanced data than accuracy
  )
  return model

# Run hyperparameter search
tuner = RandomSearch(
    tune, # function used
    objective='val_auc',  # optimizing f1 into the maximum
    max_trials=10,    # test upto 10 different hyperparameter combinations
    executions_per_trial=2, # each trial run twice and average
    directory='tuner_results' # best model saved here
)

tuner.search(
    X_train_selected,
    y_train,
    epochs=30,
    validation_data=(X_test_selected, y_test),
    callbacks=[tf.keras.callbacks.EarlyStopping(
            monitor='val_auc',
            patience=5,
            restore_best_weights=True, # return back to the best model
            mode='max'
        )]
)

# Get the best hyperparameters
best_hyper_parameters = tuner.get_best_hyperparameters(num_trials=1)[0]
print("Best hyper parameters:\n")
best_hyper_parameters.values

# Get the best layers
print("Best number of layers:", best_hyper_parameters.get('num_layers'))

for i in range(best_hyper_parameters.get('num_layers')):
    print(f"Best units in layer {i}:", best_hyper_parameters.get(f'units_{i}'))
    print("Best dropout rate:", best_hyper_parameters.get('dropout'))
    print("Best L2:", best_hyper_parameters.get('l2'))
    print("Best learning rate:", best_hyper_parameters.get('learning_rate'))

"""# **8. Training the Best Model**"""

# Build the best model
best_model = tuner.hypermodel.build(best_hyper_parameters)

# Train the best model
history = best_model.fit(
    X_train_selected,
    y_train,
    epochs=100,  # more epochs now
    batch_size=32,
    validation_data=(X_test_selected, y_test),
    callbacks=[get_callbacks()]
)

"""# **9. Comparison and Evaluation**"""

evaluate_nn(best_model, X_test_selected, y_test)  # threshold of 0.5

evaluate_nn(best_model, X_test_selected, y_test, threshold=0.4)

evaluate_nn(best_model, X_test_selected, y_test, threshold=0.3)

plot_tpr_fpr(y_test, best_model.predict(X_test_selected))

visualize_history(history)

plot_ks_chart(y_test, best_model.predict(X_test_selected), "Best Neural Network")

"""# **10. Neural Network Interpretation with SHAP**"""

# Choose background for shap
background = shap.sample(X_train_selected, 100)

# Create the explainer
explainer = shap.KernelExplainer(best_model, background)

# generate shap values
shap_values = explainer.shap_values(X_test_selected[:200])  # subset for speed

selected_mask = selector.get_support()

# Get the previously selected names
selected_feature_names = np.array(feature_names)[selected_mask]

# Summary plot of feature importance
shap.summary_plot(shap_values[:, :, 0], X_test_selected[:200],
                  feature_names=selected_feature_names,
                  plot_type='bar')
plt.tight_layout()
plt.show()

# forceplot for predictions
shap.initjs()
shap.force_plot(explainer.expected_value[0],
                shap_values[0].flatten(),
                X_test_selected[0],
                feature_names=selected_feature_names)

"""# **11. Save the Best Model**"""

# save model
best_model.save('neural_model.h5')